# Generated by Django 2.1.5 on 2019-02-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('crop_up', models.IntegerField()),
                ('crop_left', models.IntegerField()),
                ('crop_low', models.IntegerField()),
                ('crop_right', models.IntegerField()),
                ('resize_x', models.IntegerField()),
                ('resize_y', models.IntegerField()),
                ('rotate', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('bw', models.BooleanField(default=False)),
                ('share', models.BooleanField(default=True)),
            ],
        ),
    ]
