# Generated by Django 2.1.5 on 2019-02-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20190208_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shared_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shared_user',
            field=models.BooleanField(default=True),
        ),
    ]
