# Generated by Django 2.1.5 on 2019-02-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_auto_20190210_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shared_admin',
            new_name='Admin_share',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shared_user',
        ),
    ]
